### ISSUE TITLE
Revit Crashes Loading pyRevit - SentinelOne Related

### ISSUE THREAD

**Issue by zeepauls** [eirannejad/pyRevit#1055]
Hello, I have tried installing for the first time today the following version of pyRevit. 4.8.2, 4.7.6, 4.6.24. 

When I started Revit 2019, I have had two scenarios. Either the Revit splash page appears and then Revit crashed, with no error message. Or, the pyRevit sequence appears, then the Revit screen where I can select a project to open is displayed followed by Revit crashing with no error message. 

I have attached my error logs below. Thank you for your advice.

[pyRevit_2019_22916_runtime.log](https://github.com/eirannejad/pyRevit/files/5503198/pyRevit_2019_22916_runtime.log)
[pyRevit_2019_681c8dbeb6c6d8a3_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/5503199/pyRevit_2019_681c8dbeb6c6d8a3_PyRevitLabs.PyRevit.Runtime.log)

**Comment by mmcgowen23** [comment]
I am still having this issue as well. I haven't had any luck on any versions since 4.7.5. Revit load screen appears and then disappears after 15-20s.

**Comment by mmcgowen23** [comment]
My previous issue was #884

**Comment by eirannejad** [comment]
Would you mind sending a screenshot of the tabs you have on Revit UI? pyRevit seems to fail while trying to load the UI. I'm trying to see if there is any tab with special characters in the name maybe

**Comment by mmcgowen23** [comment]
![image](https://user-images.githubusercontent.com/64098364/101061075-b7f96800-3555-11eb-917d-f161f25e0e4d.png)

**Comment by eirannejad** [comment]
I think the culprit is **Enscape™**
Would you mind [disabling enscape](https://www.rhino3d.com/inside/revit/beta/reference/toubleshooting#search-for-conflicting-plugins) and see if pyRevit loads?

**Comment by mmcgowen23** [comment]
No, it still didn't load.

**Comment by eirannejad** [comment]
@mmcgowen23 Wait so in the screenshot I can see the pyRevit tabs on the end. You mean they're empty?!

**Comment by karim070505** [comment]
Similar issue I am facing for Revit 2020, Revit opens originally after opening a project revit crashes. I have no issue for Revit 2019 and 2021. I installed V4.8.4 but still now luck.
![2020-12-04 16_51_50-Autodesk Revit 2020 2 -  RAC_basic_sample_project rvt - Sheet_ A001 - Title Shee](https://user-images.githubusercontent.com/60398613/101218474-1eaf7c00-3651-11eb-9d97-76202d4c204f.png)

**Comment by eirannejad** [comment]
Would you mind closing all Revits and running `pyrevit caches clear --all` on the command line? this will clear pyRevit caches and then run Revit 2020 again

**Comment by eirannejad** [comment]
v4.8.5 is published. Would you mind testing this? If it didn't work try attaching pyRevit using the custom IronPython engine `pyrevit attach master default --installed`

**Comment by karim070505** [comment]
I installed v4.8.5 and now it crashes all revit versions. and I do not know the other methode of installation. Is there any instruction on how to attach pyRevit using the custom IronPythone engine?

**Comment by eirannejad** [comment]
Hmm. Is there any error popups? or crashes with no errors? You can use the `pyrevit attach master default --installed` on the command line to re-attach pyRevit using the new custom engine

**Comment by karim070505** [comment]
No error message or popups. right away after the revit load it crashes. and
even do not let me open a project.

**Comment by eirannejad** [comment]
Do you see any log files under `%APPDATA%/pyRevit/20XX` ? If yes would you mind sharing?

**Comment by karim070505** [comment]
In order to work, I uninstalled pyRevit from my computer completely. I do
not see any log file. I can reinstall PyRevit and send you the log file
this afternoon or tomorrow.

**Comment by mmcgowen23** [comment]
Sorry we have been swamped lately, I’ll try and get in and test pyrevit next week.

Thanks

Matt McGowen
Project Coordinator

Schwarz Hanson Architects
2570 River Park Plaza #100
Fort Worth, TX 76116
817.377.3600

NOTICE: In response to CDC guidelines regarding COVID-19, Schwarz-Hanson staff may be working remotely. We will continue to meet on site as needed. If I am unavailable at the main office phone I will still be available via email during normal office hours.

**Comment by ChrisCrosley** [comment]
I am also having this issue with all versions of Revit with v4.8.5. This is my first install of pyRevit on this machine. I have run `pyrevit attach master default --installed` as suggested above.

**Comment by ChrisCrosley** [comment]
One potentially relevant difference between my machine and a co-worker who has successfully installed pyRevit, is that I have Python 3.8 installed.

**Comment by karim070505** [comment]
Hello Ehsan,

I just installed pyRevit 4.8.6 and have the same issue with all revit
versions. Please find attached the log file.

Regards,

**Comment by eirannejad** [comment]
@n8mulder Would you mind running Revit with pyRevit 4.8.6 and let it crash. Then send me the journal file for the last session?

**Comment by n8mulder** [comment]
Journal file attached. I'm seeing API Errors/assembly conflicts...I'll let you interpret the meaning.
Thanks!
[journal.0146.txt](https://github.com/eirannejad/pyRevit/files/6258859/journal.0146.txt)

**Comment by eirannejad** [comment]
Ok great. Thanks. I published 4.8.7 yesterday with some runtime changes. It might be worth checking that one out as well.

**Comment by n8mulder** [comment]
I just tried 4.8.7...no change :(

[journal.0148.txt](https://github.com/eirannejad/pyRevit/files/6260482/journal.0148.txt)

**Comment by mmcgowen23** [comment]
Latest Log after trying 4.8.7. Tried it after running pyrevit attach master default --installed, still crashed. Also tried it after installing python as well to no avail. 

[pyRevit_2019_73f7d9a4dfca75b5_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/6444635/pyRevit_2019_73f7d9a4dfca75b5_PyRevitLabs.PyRevit.Runtime.log)

[pyRevit_2019_c3034da718573c09_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/6444636/pyRevit_2019_c3034da718573c09_PyRevitLabs.PyRevit.Runtime.log)

**Comment by ChrisCrosley** [comment]
I can confirm Revit 2021 still crashes on loading with v4.8.8 installed. Even after running `pyrevit attach master default --installed`

Here are the journal file and pyRevit log

[pyRevit_2021_901b565023656557_PyRevitLabs.PyRevit.Runtime.log](https://github.com/eirannejad/pyRevit/files/6511305/pyRevit_2021_901b565023656557_PyRevitLabs.PyRevit.Runtime.log)

[journal.0301.txt](https://github.com/eirannejad/pyRevit/files/6511295/journal.0301.txt)

Here's where things appear to go south in the log
```
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.WindowsAPICodePack assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Windows.Forms of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Core of version 3.5.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.WindowsAPICodePack.Shell assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Windows.Forms of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module PresentationFramework of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module WindowsBase of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module PresentationCore of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Drawing of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Core of version 3.5.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module WindowsFormsIntegration of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in MadMilkman.Ini assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< ::41:: Delta VM: Avail -28 -> 134211335 MB, Used +2 -> 413 MB; RAM: Avail -4 -> 18028 MB, Used +3 -> 627 MB, Peak +1 -> 630 MB 
' 0:< GUI Resource Usage GDI: Avail 9808, Used 192, User: Used 191 
' 0:< API_ERROR { : Assembly version conflict in some references in System.Reflection.Metadata assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.CSharp assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< ::41:: Delta VM: Avail -11 -> 134211325 MB, Used +2 -> 415 MB; RAM: Avail -4 -> 18024 MB, Used +4 -> 632 MB, Peak +2 -> 632 MB 
' 0:< GUI Resource Usage GDI: Avail 9808, Used 192, User: Used 191 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLabs.Common assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.VisualBasic assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
```

**Comment by n8mulder** [comment]
Same here. I keep trying every release...but only 4.7.6 continues to work.

**Comment by franchevich** [comment]
Installing pyrevit 4.8.8 will crash all my revit versions installed (r22 and r20)
any news on these crashings?

**Comment by franchevich** [comment]
The journal from %appdata%pyrevit/2022
Define: REVIT2022;REVIT2022_0
Reference: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll
Reference: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\engines\IPY277\Microsoft.Dynamic.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\engines\IPY277\Microsoft.Scripting.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\engines\IPY277\IronPython.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\engines\IPY277\IronPython.Modules.dll
Reference: C:\Program Files\Autodesk\Revit 2022\RevitAPI.dll
Reference: C:\Program Files\Autodesk\Revit 2022\RevitAPIUI.dll
Reference: C:\Program Files\Autodesk\Revit 2022\AdWindows.dll
Reference: C:\Program Files\Autodesk\Revit 2022\UIFramework.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\engines\IPY277\pyRevitLoader.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\pyRevitLabs.Common.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\pyRevitLabs.CommonWPF.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\pyRevitLabs.MahAppsMetro.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\pyRevitLabs.NLog.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\pyRevitLabs.TargetApps.Revit.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\pyRevitLabs.PyRevit.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\pyRevitLabs.Emojis.dll
Reference: C:\Program Files\Autodesk\Revit 2022\Xceed.Wpf.AvalonDock.dll
Reference: C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\bin\engines\CPY385\pyRevitLabs.PythonNet.dll
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\ScriptConsoleUtils.cs(68,50): warning CS0618: 'IndependentTag.TaggedLocalElementId' is obsolete: 'This property is deprecated in Revit 2022 and will be removed in a later version of Revit. We suggest you use the `GetTaggedLocalElementIds()` method instead.'
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\EventTelemetry.cs(137,27): warning CS0618: 'PrintParameters.UserDefinedMarginX' is obsolete: 'This property is obsolete. Use OriginOffsetX instead.'
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\EventTelemetry.cs(138,27): warning CS0618: 'PrintParameters.UserDefinedMarginY' is obsolete: 'This property is obsolete. Use OriginOffsetY instead.'
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\UpdaterListener.cs(3,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\UpdaterListener.cs(4,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\UpdaterListener.cs(5,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\ScriptIO.cs(4,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\CLREngine.cs(10,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\CLREngine.cs(19,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\CLREngine.cs(11,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\EventHandling.cs(2,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\EventTelemetry.cs(7,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\EventHandling.cs(11,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\ScriptTelemetry.cs(4,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\UpdaterListener.cs(2,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\UpdaterListener.cs(8,1): hidden CS8019: Unnecessary using directive.
C:\Users\JuanCarlosf\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime\ScriptTelemetry.cs(6,1): hidden CS8019: Unnecessary using directive.

**Comment by franchevich** [comment]
[journal.0042.txt](https://github.com/eirannejad/pyRevit/files/6618955/journal.0042.txt)
[journal.0042.worker1.log](https://github.com/eirannejad/pyRevit/files/6618956/journal.0042.worker1.log)

**Comment by ChrisCrosley** [comment]
On my machine, I think that this bug may be caused by SentinelOne terminating Revit when it's trying to load the pyRevit add-in. 

I'm going to try to get IT to look at it this week and I'll post an update. 

We just had a very similar issue with Ladybug components crashing Rhino/Grasshopper - which also uses Python and runs from a local user folder - that was resolved by whitelisting them in SentinelOne.

**Comment by franchevich** [comment]
I'm trying in another computer w/o SentinelOne and is up and running, thanks for the tip Chris...!!!

**Comment by n8mulder** [comment]
This is promising news. Our IT uses SentinelOne. pyRevit was added as an
exclusion and the file hash extracted (pyRevit 4.8.8).  However, Revit
continues to crash/close on open with pyRevit installed. Can you provide
detailed instructions on what you did to get it fixed? Do both pyRevit and
Revit need to be excluded/whitelisted?

Thanks!

**Comment by ChrisCrosley** [comment]
Yes, we also had to add all versions of Revit as well.

/
Chris Crosley AIA
Architect
DELV DESIGN
O +1 317.296.7400
M +1 513.225.8552
––––
212 W 10TH ST
SUITE F125
INDIANAPOLIS, IN 46202
DELVdesign.com
Registered Architect: IN
________________________________

**Comment by n8mulder** [comment]
Great news! SentinelOne was the issue for us as well! Interestingly it was not generating alerts that it was blocking it so presumably it went undetected this whole time. We excluded the paths for pyRevit and all Revit versions.

Thanks @ChrisCrosley!

**Comment by eirannejad** [comment]
Great to know! Thank you!

**Comment by unevenload** [comment]
Chris or n8mulder- Can you share the paths you whitelisted? @ChrisCrosley @n8mulder

**Comment by ChrisCrosley** [comment]
you need all Revit versions and the pyRevit AppData folder, so:

C:\Program Files\Autodesk\Revit 2020\Revit.exe
C:\Program Files\Autodesk\Revit 2021\Revit.exe
[user]\AppData\Roaming\pyRevit\

**Comment by unevenload** [comment]
Thanks so much! @ChrisCrosley

**Comment by guidelagui** [comment]
Currently testing SentinelOne, InProcessClient64.dll look like not working with some software. I think whitelisting folder is not a good idea, this can be a king of precise attack for AEC firms. Software hash is better but need to be maintain for each update. No go for us.

**Comment by SinnwellR** [comment]
Can anyone give me some specific instructions on whitelisting pyRevit in SentinelOne?  Because it doesn't create an Incident or Alert, I can't easily add an exception for it. I don't want to exclude entire folders, I need to be able to create a hash exception and then I will limit that to the group of folks who run pyRevit.  I also opened a bug report with pyRevit just in case something can be done to change whatever the suspect behavior SentinelOne doesn't like.  My guess is that other EDR/XDR products might also have issues with it so that might be a better fix if it is reasonable.

**Comment by guidelagui** [comment]
We test different solution and because sentinel one interfer with pyrevit interfer with other product that use specific function is the graphic card we select a different solution named crowdstrike. Work really well.

You can whitelist a folder, only sale people will tell you that, never a good thing do do in security especially if it’s the main production software it can be specifically target in AEC. Too much folder to do. You can whitelist the application hash manually for all software interacting with pyrevit and Revit but hard to maintain for each patch autodesk release…

**Comment by bobbieqc** [comment]
Really problematic, we are using Sentinel one too, here is what PYREVIT env shows after installing 5.1 whre both revit 2023 latest version and 02024 crashes 

<img width="1018" height="533" alt="Image" src="https://github.com/user-attachments/assets/3cbefaf4-dc13-4aa1-b44f-265018f7b418" />

**Comment by jmcouffin** [comment]
Please uninstall old version and download WIP installers from the actions tab or from the https://pyrevitlabs.io website using the orange button and report. @bobbieqc

**Comment by bobbieqc** [comment]
After trying to install latest WIP version here the result from Pyrevit env, 2023 and 2024 are installe on this computer running windows 10:

Software are installed on two physicale disk c: and d:

Unknown | Product: "2024.3.3" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2024\pyRevit.addin"
Unknown | Product: "Autodesk Revit 2023" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2023\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Bédard\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
[https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpyrevitlabs%2FpyRevit%2Fraw%2Fmaster%2Fextensions%2Fextensions.json&data=05%7C02%7Cleclerc%40archi.ca%7Caafd7ccbe136415e98ba08dde710ec14%7C91064873ea984301b93be0872ac39c70%7C0%7C0%7C638920782106629248%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=4pxVAbjVXRD7mkVHgJ2jtDHgTuyA03IaWvEGb2PRPJk%3D&reserved=0)
==> Extension Sources - Additional
==> Installed Revits
2024.3.3 | Version: 24.3.30.11 | Build: 20250516_1515(x64) | Language: 1033 | Path: "D:\Autodesk\Revit 2024"
Autodesk Revit 2023 | Version: 23.1.80.30 | Build: 20250724_1515(x64) | Language: 1033 | Path: "D:\Autodesk\Revit 2023"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: CORRIVEAUGIRARD\bedard
Active User: CORRIVEAUGIRARD\bedard
Admin Access: No
%APPDATA%: "C:\Users\Bédard\AppData\Roaming"
Latest Installed .Net Framework: 8.0.19
No .Net Target Packs are installed.
Installed .Net-Core Target Packs: v8.0.413
pyRevit CLI v5.2.0.25181+1332.ad837f1fc6ac89979e64710991eb6d846b63c109

**Comment by jmcouffin** [comment]
> After trying to install latest WIP version here the result from Pyrevit env, 2023 and 2024 are installe on this computer running windows 10:
> 
> Software are installed on two physicale disk c: and d:
> 
> Unknown | Product: "2024.3.3" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2024\pyRevit.addin" Unknown | Product: "Autodesk Revit 2023" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2023\pyRevit.addin" ==> Installed Extensions ==> Default Extension Search Path C:\Users\Bédard\AppData\Roaming\pyRevit\Extensions ==> Extension Search Paths ==> Extension Sources - Default [https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpyrevitlabs%2FpyRevit%2Fraw%2Fmaster%2Fextensions%2Fextensions.json&data=05%7C02%7Cleclerc%40archi.ca%7Caafd7ccbe136415e98ba08dde710ec14%7C91064873ea984301b93be0872ac39c70%7C0%7C0%7C638920782106629248%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=4pxVAbjVXRD7mkVHgJ2jtDHgTuyA03IaWvEGb2PRPJk%3D&reserved=0) ==> Extension Sources - Additional ==> Installed Revits 2024.3.3 | Version: 24.3.30.11 | Build: 20250516_1515(x64) | Language: 1033 | Path: "D:\Autodesk\Revit 2024" Autodesk Revit 2023 | Version: 23.1.80.30 | Build: 20250724_1515(x64) | Language: 1033 | Path: "D:\Autodesk\Revit 2023" ==> Running Revit Instances ==> User Environment Microsoft Windows 10 [Version 10.0.19045] Executing User: CORRIVEAUGIRARD\bedard Active User: CORRIVEAUGIRARD\bedard Admin Access: No %APPDATA%: "C:\Users\Bédard\AppData\Roaming" Latest Installed .Net Framework: 8.0.19 No .Net Target Packs are installed. Installed .Net-Core Target Packs: v8.0.413 pyRevit CLI v5.2.0.25181+1332.ad837f1fc6ac89979e64710991eb6d846b63c109

And it works? @bobbieqc

**Comment by bobbieqc** [comment]
Still not working.

**Comment by bobbieqc** [comment]
Nope!

**Comment by jmcouffin** [comment]
Your install seems ok(ish) so look for sentinel one proper setup, both Revit and pyrevit folders must be cleared

**Comment by bobbieqc** [comment]
Merci Jean Marc,

Sentinel One est vraiment le problème, et il ne génère aucun message
d'erreur... quand il bloque, tout est fonctionnel en version 5.2...après
avoir désactivé SentinelOne pour les répertoires de Pyrevit
