### ISSUE TITLE
Pre Flight Check - Model Check "'Chart' is undefined"

### ISSUE THREAD

**Issue by DuncanLithgow** [eirannejad/pyRevit#1176]
**Describe the bug**
Script error message on running the Pre Flight Check - Model Check

**To Reproduce**
1. Just run the tool

**Expected behavior**
Should run without errors

**Screenshots**
![billede](https://user-images.githubusercontent.com/3223028/109174355-1022bd80-7785-11eb-8aaa-92c5904ab096.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - pyRevit Version 4.5.8
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

`pyrevit env`

```Microsoft Windows [Version 10.0.17763.1757]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\dli>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.5" | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2021.1.1" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.3" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
master | Product: "2017.2.5 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\dli\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\dli\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2021.1.1 | Version: 21.1.10.26 | Build: 20200909_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.3 | Version: 20.2.30.42 | Build: 20200826_1250(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017\"
==> Running Revit Instances
PID: 9452 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.17763]
Executing User: RAMBOLL\DLI
Active User: RAMBOLL\DLI
Admin Access: No
%APPDATA%: "C:\Users\dli\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.5.0

C:\Users\dli>```

**Additional context**
nul

**Comment by eirannejad** [comment]
Hmm this has got something to do with the output window not being able to download charts.js Let me see if I can include it with pyRevit and be done with this

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by lexiko80-LPA** [comment]
Hi, i'm still observing the same issue


C:\WINDOWS\system32>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
pyRevit-LPA-488-idw1003 | Deploy: "" | Branch: "master" | Version: "4.8.8" | Path: "C:\Repos\pyRevit488-idw1003\pyRevit-LPA-488"
==> Attachments
pyRevit-LPA-488-idw1003 | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Repos\pyRevit488-idw1003\pyRevit-LPA-488" | AllUsers
pyRevit-LPA-488-idw1003 | Product: "2021 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Repos\pyRevit488-idw1003\pyRevit-LPA-488" | AllUsers
pyRevit-LPA-488-idw1003 | Product: "2020.2.4" | Engine: IPY277 (277) | Path: "C:\Repos\pyRevit488-idw1003\pyRevit-LPA-488" | AllUsers
pyRevit-LPA-488-idw1003 | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Repos\pyRevit488-idw1003\pyRevit-LPA-488" | AllUsers
pyRevit-LPA-488-idw1003 | Product: "2016.1.9 Security Fix" | Engine: IPY277 (277) | Path: "C:\Repos\pyRevit488-idw1003\pyRevit-LPA-488" | AllUsers
==> Installed Extensions
pyLPA | Type: Unknown | Repo: "" | Installed: "C:\Repos\pyRevit488-idw1003\Extensions\pyLPA.extension"
==> Default Extension Search Path
C:\Users\admin_akotzambasis\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Repos\pyRevit488-idw1003\Extensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2022 | Version: 22.0.10.28 | Build: 20210616_0115(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021 First Customer Ship | Version: 21.0.0.383 | Build: 20200220_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.4 | Version: 20.2.40.65 | Build: 20210420_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
2016.1.9 Security Fix | Version: 16.0.1218.0 | Build: 20190508_0715(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2016\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: LPA\admin_akotzambasis
Active User:
Admin Access: Yes
%APPDATA%: "C:\Users\admin_akotzambasis\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.8.0

**Comment by colinmccroskey** [comment]
Still getting this error in 4.8.12.22247, with Revit 2023.
Did I miss an update?
