### ISSUE TITLE
pyRevit does not work when independent IronPython is installed

### ISSUE THREAD

**Issue by CyrilWaechter** [eirannejad/pyRevit#180]
Hello,

1. I tried to update pyRevit to 4.3 and was unable to (unable to get current_sessionid or something like this). 
2. Then I tried to uninstall pyRevit and reinstall it. It worked for few minutes.
3. Then I tried to add my custom extension folder. It didn't work.
4. After maybe 2 tries I got the following message.
![image](https://cloud.githubusercontent.com/assets/9622862/24831446/b59bff38-1c99-11e7-953b-626a98d0d382.png)
5. I tried to uninstall/install pyRevit more than 10 times. Between some of my tries I cleaned registry. Tried to find any pyRevit related file on my computer to delete to try to do a clean install. I'm unable to launch pyRevit at all. I always get error displayed at point 4.

I tried to find LibGit2Sharp files, They were in pyRevit folder as they are supposed to. I tried to install pyRevit in different folders (%user% and directly on C:/). I'm short of ideas right now.

**Comment by eirannejad** [comment]
@CyrilWaechter I'm sorry for the trouble this has caused. Let's see what's the issue:

- pyRevit doesn't record anything in your windows registry or any other location other than the installation folder and user appdata.
- All pyRevit temporary files are under `%appdata%\pyRevit\<revit version>` for example for Revit 2017 they're in `%appdata%\pyRevit\2017`.
- The `LibGit2Sharp` files are all under the pyRevit installation folder and not anywhere else.

**Cleanup:**
First, I'd suggest deleting the `%appdata%\pyRevit` folder completely. This will clear all temporary files and configurations for pyRevit. Also go to the `%appdata%\Autodesk\Revit\Addins` folder and delete `pyRevit.addin` in each folder corresponding to installed Revit versions.

This should effectively cleanup all of pyRevit from your system. Then do a fresh install and let me know if you still have issues.

**Comment by CyrilWaechter** [comment]
@eirannejad 
I tried to do what you advised carefully step by step but I still have the same issue.

Then I checked last software installed. List was including ironpython 2.7.7. I thought «Strange ! What if I remove it ?» and pyRevit suddenly worked. So I was able to reproduce the case.
- Install IronPython 2.7.7 => pyRevit doesn't work anymore
- Remove IronPython 2.7.7 => pyRevit works

I don't know how but it looks like there is some kind of interaction between pyRevit 4.3 and Ironpython 2.7.7 despite the fact ironpython 2.7.7 is already included and running in pyRevit 4.3.

I hope these additional informations will help.

**Comment by eirannejad** [comment]
Interesting. I'll try to see if I can resolve this conflict.

**Comment by eirannejad** [comment]
Resolved. Will be published with the next version.

**Comment by eirannejad** [comment]
Will be published in 4.4 soon

**Comment by Claukopietz** [comment]
Hello.

I'm having the same issue described above with pyRevit4.8.8. Ihave followed all the steps you suggested and still get the ironpython error and then pyRevit will not be installed.
Any suggestion or tip if I'm missing something?

Best regards,
Claudia

**Comment by vosepherus** [comment]
I'm having this same problem trying to get pyRevit to work on Revit 2023. Seems like IronPython is a constant problem. Can anone explain how to uninstall it, or for that matter what it actually does? People seem to be able to uninstall it without any adverse effects. I don't see it in my list of installed programs though, so I have no idea how to get rid of it.
