### ISSUE TITLE
Viewport Location on Sheet should align based on absolute location not bbox center

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#190]
I thought this was resolved in an earlier release and it seems to be broken:

Viewports with different boundaries don't align.  

Exaggerated Example:
![image](https://cloud.githubusercontent.com/assets/14113080/25500436/07d25e7e-2b5d-11e7-9fad-2ca5bc984ed9.png)

![image](https://cloud.githubusercontent.com/assets/14113080/25500489/31a5524c-2b5d-11e7-9b19-4523c000974f.png)

**Comment by gtalarico** [comment]
@thazell 
latest view port placement tools vp on pyrevitplus works as expected. 
I implemented a fix a while ago, but forgot to push it to the repo.
Also has a feature to align viewport across multiple sheets in one click, although it's a bit limited right now.

https://github.com/gtalarico/pyrevitplus/tree/master/pyRevitPlus.tab/ViewPorts.panel/ViewportPlacement.stack3

**Comment by thazell** [comment]
Thanks @gtalarico.

**Comment by eirannejad** [comment]
Resolved for v4.5rc

**Comment by eirannejad** [comment]
v4.5rc is available now:
http://eirannejad.github.io/pyRevit/pyrevit/update/2017/12/02/45rc.html

**Comment by brankulo** [comment]
i still have this very same issue running version 4.6.19 under revit 2019. 
the viewports do not not align. any idea why?

**Comment by thazell** [comment]
Can you check if the views you are using have scope boxes and report?

**Comment by brankulo** [comment]
nope, no scope boxes involved.
