### ISSUE TITLE
Unable to Purge the unused parameters in the families

### ISSUE THREAD

**Issue by Abdoo1212** [eirannejad/pyRevit#347]
Hi, I am facing a problem once I try to use the tool of Purge and Reset all family parameters. As it gives me a message saying I should sync the model then press Ok, however there is no botton for Ok.

![1](https://user-images.githubusercontent.com/40456038/41708155-625c92be-7572-11e8-88fb-474b2126c552.png)

Thanks in Advance.
Abdoo

**Comment by eirannejad** [comment]
Woooops! Will fix soon :)

**Comment by eirannejad** [comment]
Resolved.

**Comment by Abdoo1212** [comment]
Hi Eirannejad, Do I have to do anything else to get the solved tool as I still have the same problem. Revit asks me to press OK but I cannot find it. Sorry I am quite new in using the PyRevit plugin.

Thanks and Kind Regards,
Abdelrahman

**Comment by eirannejad** [comment]
Update your pyRevit. `pyRevit tab > PyRevit panel > Update`

**Comment by eirannejad** [comment]
This is odd. What’s your pyRevit version? Check the about box. Try reinstalling pyRevit. Seems like recent github changes have broken the update system. I’ll check it out soon

**Comment by Abdoo1212** [comment]
![image](https://user-images.githubusercontent.com/40456038/41756665-3c11f0b0-7610-11e8-8ca8-81d3ef1f4923.png)

Isn't it the latest one?

**Comment by eirannejad** [comment]
No you’re a couple of fixes behind. Reinstall and I’ll check the update system this weekend. It might be broken.

**Comment by Abdoo1212** [comment]
Alright. Thanks alot for your efforts Eirannejad. I will reinstall it now. 
Do you suggest to activate the option of Auto Update in during the startup or this will take long time once I open any Revit file?

Best Regards

**Comment by eirannejad** [comment]
You can leave it off for now. Let me fix the update system first so your repo is updated correctly.

**Comment by Abdoo1212** [comment]
Ok, Thanks a lot!
