### ISSUE TITLE
pyRevit 4.6.4 Setup Wizard ended prematurely

### ISSUE THREAD

**Issue by cillianjohn** [eirannejad/pyRevit#397]
Hi. I'm getting this error when trying to install pyRevit on my Windows 10 Pro machine. Windows version 10.0.17134.  Error log attached below.

![pyrevit 4 6 4_setupwizardended](https://user-images.githubusercontent.com/17741816/47635393-81261c00-db5d-11e8-887f-9c79e351fc29.JPG)

[MSI543B.LOG](https://github.com/eirannejad/pyRevit/files/2524240/MSI543B.LOG)

**Comment by eirannejad** [comment]
Do you have a `.` in your machine user name? What's `%appdata%` on your machine?

**Comment by cillianjohn** [comment]
Yes there is a "." in my machine user name. It's my work pc that I have admin rights for.  
%appdata% is a hidden folder where Windows apps often store their data and settings and each Windows user account has its own.

**Comment by eirannejad** [comment]
@cillianjohn I mean what does `%appdata%` expand to on your machine? Wanted to see if there is a dot in your username. Thanks for the info

**Comment by eirannejad** [comment]
No reponse. Assuming it's resolved with the new installer for 4.6.5

**Comment by cillianjohn** [comment]
Hi,
I'm still getting the same error message when trying to install 4.6.5. Error log attached. 
I'm trying to install it here on my machine: C:\Users\cillian.warfield\AppData\Roaming\pyRevit-Master\
[MSI56D5_20181107.LOG](https://github.com/eirannejad/pyRevit/files/2556347/MSI56D5_20181107.LOG)

**Comment by cillianjohn** [comment]
Should I open a new issue for this since my problem now relates to 4.6.5 (and this issue has been closed)?
Thanks

**Comment by eirannejad** [comment]
Merged into: https://github.com/eirannejad/pyRevit/issues/421

**Comment by TyHearn** [comment]
Did this ever get resolved? I'm having the same issue when trying to uninstall.

**Comment by eirannejad** [comment]
No. Merged it into #421 so all installer issues are organized under the same issue

**Comment by cillianjohn** [comment]
Installed v4.6.6. Issue resolved. Thanks
