### ISSUE TITLE
Change path for loading pyRevit core

### ISSUE THREAD

**Issue by MatthewJohnsonVMDO** [eirannejad/pyRevit#515]
I'm working on implementing pyRevit in my office.  I've had great success setting up an extension on our servers for custom tools I've created, and now I wish that users could also load the core pyRevit tools from a remote location instead of their own computer.  In other words, I wish that there was an option in Settings under Custom Extension Directories to remove the default directory and have pyRevit look in the custom directory for everything.

I'm new to pyRevit and python in general, but this is already saving me and my office tons of time, so thank you for all the hard work that's gone into developing this tool.  My apologies if what I'm asking for is already possible and I've just overlooked how to do it.

**Comment by andrewberes** [comment]
I implemented this in the same way you describe at a previous employer. 
Simply install pyrevit on a network drive (copy all of the source files from the pyRevit folder in your program data) and modify the .addin file under Audodesk/Revit/Addins to point to that network location. This will tell revit at startup to look to the network for the addin's loader files. 

There are also some built in pyRevit tools to manage who can access what extensions via their usernames. For example, i kept a dev extension that only a few of us could see, a sustainability tools extension for our green team and then a general office extension of tools for everyone.

**Comment by MatthewJohnsonVMDO** [comment]
Thanks for your reply Andrew.  I copied the files from pyRevit-Master and edited the .addin file and it appeared to work, but there's still an error popping up when I hit "Settings".  I'll check out the YouTube channel to see what I missed.

**Comment by eirannejad** [comment]
Please watch this video on [deploying pyRevit](https://www.youtube.com/watch?v=hnlAEEfzhok) and take a look at [CLI help](https://github.com/eirannejad/pyRevit/blob/master/README_CLI.md)

You should be using pyrevit CLI tool to deploy the `core` or `corex` deployment to the users. The downloaded pyRevit deployes the `basepublic` deployment. `core` includes the pyRevit core only and `corex` include the core plus the single pyRevit panel. [See deployments here](https://github.com/eirannejad/pyRevit/blob/master/pyRevitfile)

Then you can place the `pyRevitTools.extension` directory somewhere on the network and add the path to pyRevit settings.

```
pyrevit clone myclone corex --dest="destination/path"
```
