### ISSUE TITLE
CLI `extensions sources add` command doesn't work

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#746]
**Describe the bug**
Hey Ehsan, thank you for the new release! 
I am doing final checks before deploying new version in my org. Just found an issue.

Command `pyrevit extensions sources add D:\Sicherung\pyRevit_extensions.json --debug` doens't change `.ini` file.

`pyrevit attach master 277 --installed`

**To Reproduce**
Do fresh installation of 4.7.4. Run cli command (see above).

The result is:
```pyrevit extensions sources add D:\Sicherung\pyRevit_extensions.json --debug
add = True
extensions = True
sources = True
<source_json_or_url> = D:\Sicherung\pyRevit_extensions.json
Debug: Checking for all: wiki
Debug: Missing: wiki
Debug: Checking for all: blog
Debug: Missing: blog
Debug: Checking for all: docs
Debug: Missing: docs
Debug: Checking for all: source
Debug: Missing: source
Debug: Checking for all: youtube
Debug: Missing: youtube
Debug: Checking for all: support
Debug: Missing: support
Debug: Checking for all: env
Debug: Missing: env
Debug: Checking for all: update
Debug: Missing: update
Debug: Checking for all: clone
Debug: Missing: clone
Debug: Checking for all: clones
Debug: Missing: clones
Debug: Checking for all: attach
Debug: Missing: attach
Debug: Checking for all: detach
Debug: Missing: detach
Debug: Checking for all: attached
Debug: Missing: attached
Debug: Checking for all: switch
Debug: Missing: switch
Debug: Checking for all: extend
Debug: Missing: extend
Debug: Checking for all: extensions
Debug: Checking for all: search
Debug: Missing: search
Debug: Checking for any: info,help,open
Debug: Checking for all: delete
Debug: Missing: delete
Debug: Checking for all: origin
Debug: Missing: origin
Debug: Checking for all: paths
Debug: Missing: paths
Debug: Checking for any: enable,disable
Debug: Checking for all: sources
dfsdfsd
Debug: Checking for all: add
Debug: Normalized as "D:\Sicherung\pyRevit_extensions.json"
Debug: Try getting config as list "environment:sources"
Debug: Try getting config "environment:sources"
Debug: Config "environment:sources" not set.
Debug: Registering extension lookup source "D:\Sicherung\pyRevit_extensions.json"
```

Ini wasn't changed:
```
[environment]
clones = {"master":"D:\\Users\\aleksei.melnikov\\AppData\\Roaming\\pyRevit-Master"}
```

**Expected behavior**
I am expecting to get `sources` option in .ini.

**Desktop (please complete the following information):**
 - OS: Win 10
 - pyRevit Version 4.7.4
 - pyRevit Environment: 
```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7.4" | Path: "D:\Users\aleksei.melnikov\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2019.2.1" | Engine: 277 | Path: "D:\Users\aleksei.melnikov\AppData\Roaming\pyRevit-Master" | Manifest: "D:\Users\aleksei.melnikov\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
D:\Users\aleksei.melnikov\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2019.2.1 | Version: 19.2.10.7 | Build: 20190225_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.18362]
Executing User: HWPNET\aleksei.melnikov
Active User: HWPNET\aleksei.melnikov
Admin Access: No
%APPDATA%: "D:\Users\aleksei.melnikov\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.17.0.0
```

**Comment by eirannejad** [comment]
Resolved and will be published with the next release.

**Comment by guusgooskens** [comment]
Hey Ehsan, sorry to hijack this post, but I am still experiencing an issue with the same CLI command.
It works if I provide the source .json directly (as this post):
```
pyrevit extensions sources add C:\Temp\extensions.json
```
But when I try adding a url hosted location as additional source ([following the wiki](https://www.notion.so/Manage-pyRevit-extensions-fa853768e94240b5b59803e5d7171be3#4eb8c8f8683f4cb6a8f5124ea09fd522)):
```
pyrevit extensions sources add "https://www.gitlab.arup.com/bim-to-bam/pyrevit-extensions-arup/-/raw/master/extensions.json"
```

it gives this error:
```
Error: The given path's format is not supported. (System.NotSupportedException)
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at pyRevitLabs.Common.Extensions.StringExtensions.NormalizeAsPath(String path)
   at pyRevitLabs.PyRevit.PyRevitExtensions.GetRegisteredExtensionLookupSources()
   at pyRevitCLI.PyRevitCLIExtensionCmds.PrintExtensionLookupSources()
   at pyRevitCLI.PyRevitCLIAppCmds.MakeEnvReport(Boolean json)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)
```
Could this issue be reopened?
