### ISSUE TITLE
Renaming sheets

### ISSUE THREAD

**Issue by AhmedeMostafa** [eirannejad/pyRevit#880]
Under the sheets tab commands "Select sheets" and "Rename selected sheets" they have the same description which is "Change the selected sheet names".

I can't see that "Select sheets" command do anything and with the "Change the selected sheet names" command I can only change the sheet names to lower or upper case and that's it.

**To Reproduce**
1. Go to 'pyRevit tab'
2. Click on 'Sheets'
3. Scroll down to 'Rename Selected Sheets'

**Expected behavior**
I'm expecting to be able to rename any or all of my sheets at once.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - pyRevit Version v4.7.5

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by RugDouglas** [comment]
This exact issue seems to be present again in the latest release v4.8.16.24121

**Comment by SadRevitUser69** [comment]
This is still an issue in v6.4.0. Same behaviour/steps mentioned by OP.
